import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  // `supabase/functions/mcp/index.ts` is generated by the Lovable MCP tooling
  // and is regenerated on every build, so hand edits there are always lost.
  { ignores: ["dist", "supabase/functions/mcp/index.ts"] },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      "@typescript-eslint/no-unused-vars": "off",
      // Reported, not fatal: the Deno edge functions deliberately work with
      // untyped Postgres/JSON payloads. Every other rule stays an error.
      "@typescript-eslint/no-explicit-any": "warn",
    },
  },
  {
    // Generated shadcn/ui primitives: the empty interface pattern comes
    // straight from the generator. Narrowly scoped to that folder only.
    files: ["src/components/ui/**/*.{ts,tsx}"],
    rules: { "@typescript-eslint/no-empty-object-type": "off" },
  },
);
