import type { RetailCardDef } from './types';

// ── Public Retail Card Definitions ──
// Maps to catalogue products by eligibleProductIds.
// The UI renders these cards — never raw catalogue data.

export const broadbandRetailCards: RetailCardDef[] = [
  {
    id: 'essential',
    publicTitle: 'ESSENTIAL FIBRE',
    category: 'Essential Fibre',
    tagline: 'Reliable everyday broadband for browsing, email and streaming.',
    description: 'Reliable everyday broadband for browsing, email and streaming.',
    features: [
      'Up to 80Mbps download',
      'Price Lock 24 available',
      'Flex 30 rolling available',
      'Bring your own router for £0',
      'Setup from £0 where available',
      'Final price confirmed before order',
    ],
    speedLabel: 'Up to 80Mbps',
    eligibleProductIds: ['sogea-40-10-1m', 'sogea-80-20-1m', 'fttp-80-20-tt'],
    popular: false,
    serviceType: 'broadband',
    publicPricePrefix: 'From',
    publicSetupText: 'Setup from £0 where available',
    publicTagline: 'Reliable everyday broadband for browsing, email and streaming.',
    publicFeatures: [
      'Up to 80Mbps download',
      'Price Lock 24 available',
      'Flex 30 rolling available',
      'Bring your own router for £0',
      'Router options at checkout',
      'Final price confirmed before order',
    ],
    publicDisclaimer: 'Final price depends on address, plan type, router and setup.',
  },
  {
    id: 'superfast',
    publicTitle: 'SUPERFAST FIBRE',
    category: 'Superfast Fibre',
    tagline: 'Great for streaming, home working and busy households.',
    description: 'Great for streaming, home working and busy households.',
    features: [
      '150–330Mbps options',
      'Price Lock or Flex 30',
      'No forced router bundle',
      'First bill preview',
      'Optional priority support',
      'Final price confirmed before order',
    ],
    speedLabel: '150–330Mbps options',
    eligibleProductIds: ['fttp-160-tt', 'fttp-220-tt', 'fttp-330-tt'],
    popular: true,
    serviceType: 'broadband',
    publicPricePrefix: 'From',
    publicSetupText: '',
    publicTagline: 'Great for streaming, home working and busy households.',
    publicFeatures: [
      '150–330Mbps options',
      'Price Lock or Flex 30',
      'No forced router bundle',
      'First bill preview',
      'Optional priority support',
      'Final price confirmed before order',
    ],
    publicDisclaimer: 'Final price depends on address, plan type, router and setup.',
  },
  {
    id: 'ultrafast',
    publicTitle: 'ULTRAFAST FIBRE',
    category: 'Ultrafast Fibre',
    tagline: 'Built for busy homes and businesses that need headroom.',
    description: 'Built for busy homes and businesses that need headroom.',
    features: [
      '500Mbps–1Gbps where available',
      'Bring your own router or add premium WiFi',
      'Gigabit options where available',
      'Static IP available on selected services',
      'Clear setup and add-on pricing',
      'Final price confirmed before order',
    ],
    speedLabel: '500Mbps–1Gbps where available',
    eligibleProductIds: ['fttp-500-tt', 'fttp-550-cf'],
    popular: false,
    serviceType: 'broadband',
    publicPricePrefix: 'From',
    publicSetupText: '',
    publicTagline: 'Built for busy homes and businesses that need headroom.',
    publicFeatures: [
      '500Mbps–1Gbps where available',
      'Bring your own router or add premium WiFi',
      'Gigabit options where available',
      'Static IP available on selected services',
      'Clear setup and add-on pricing',
      'Final price confirmed before order',
    ],
    publicDisclaimer: 'Final price depends on address, plan type, router and setup.',
  },
  {
    id: 'gigabit',
    publicTitle: 'GIGABIT FIBRE',
    category: 'Gigabit Fibre',
    tagline: 'Top-tier full fibre for large households and small businesses.',
    description: 'Top-tier full fibre for large households and small businesses.',
    features: [
      'Up to 1Gbps where available',
      'Bring your own router for £0',
      'Static IP available',
      'Price Lock or Flex 30',
      'Clear setup and add-on pricing',
      'Final price confirmed before order',
    ],
    speedLabel: 'Up to 1Gbps where available',
    eligibleProductIds: ['fttp-1000-tt', 'fttp-1000-cf'],
    popular: false,
    serviceType: 'broadband',
    publicPricePrefix: 'From',
    publicSetupText: '',
    publicTagline: 'Top-tier full fibre for large households and small businesses.',
    publicFeatures: [
      'Up to 1Gbps where available',
      'Bring your own router for £0',
      'Static IP available',
      'Price Lock or Flex 30',
      'Clear setup and add-on pricing',
      'Final price confirmed before order',
    ],
    publicDisclaimer: 'Final price depends on address, plan type, router and setup.',
  },
];

export const landlineRetailCard: RetailCardDef = {
  id: 'digital-voice',
  publicTitle: 'Digital Voice Line',
  category: 'Digital Home Phone',
  tagline: 'Digital home phone that works through your broadband',
  description: 'Digital home phone that works through your broadband',
  features: [
    'Digital voice line included',
    'Crystal clear HD calls',
    'Caller display',
    'Free voicemail',
    'No contracts - cancel anytime',
    'Works with standard home phones',
  ],
  speedLabel: '',
  eligibleProductIds: ['home-phone-payg'],
  popular: true,
  serviceType: 'landline',
  publicPricePrefix: 'From',
  publicSetupText: '',
  publicTagline: 'Digital home phone that works through your broadband',
  publicFeatures: [
    'Digital voice line included',
    'Crystal clear HD calls',
    'Caller display',
    'Free voicemail',
    'No contracts - cancel anytime',
    'Works with standard home phones',
  ],
  publicDisclaimer: '',
};

// SIM retail cards — no ICUK data uploaded, keep current prices exactly
export const simRetailCards: RetailCardDef[] = [
  {
    id: 'sim-starter',
    publicTitle: 'Starter',
    category: 'SIM',
    tagline: 'For light users and second phones',
    description: 'For light users and second phones',
    features: ['5GB 5G data', 'Unlimited UK calls', 'Unlimited texts', 'EU roaming included', 'No contracts - cancel anytime', 'Free SIM delivery'],
    speedLabel: '5GB',
    eligibleProductIds: [],
    popular: false,
    serviceType: 'sim',
    publicPricePrefix: '',
    publicSetupText: '',
    publicTagline: 'For light users and second phones',
    publicFeatures: ['5GB 5G data', 'Unlimited UK calls', 'Unlimited texts', 'EU roaming included', 'No contracts - cancel anytime', 'Free SIM delivery'],
    publicDisclaimer: '',
  },
  {
    id: 'sim-essential',
    publicTitle: 'Essential',
    category: 'SIM',
    tagline: 'Perfect for everyday use',
    description: 'Perfect for everyday use',
    features: ['15GB 5G data', 'Unlimited UK calls', 'Unlimited texts', 'EU roaming included', 'No contracts - cancel anytime', 'Data rollover'],
    speedLabel: '15GB',
    eligibleProductIds: [],
    popular: false,
    serviceType: 'sim',
    publicPricePrefix: '',
    publicSetupText: '',
    publicTagline: 'Perfect for everyday use',
    publicFeatures: ['15GB 5G data', 'Unlimited UK calls', 'Unlimited texts', 'EU roaming included', 'No contracts - cancel anytime', 'Data rollover'],
    publicDisclaimer: '',
  },
  {
    id: 'sim-plus',
    publicTitle: 'Plus',
    category: 'SIM',
    tagline: 'For the social media enthusiasts',
    description: 'For the social media enthusiasts',
    features: ['50GB 5G data', 'Unlimited UK calls', 'Unlimited texts', '30GB EU roaming', 'No contracts - cancel anytime', 'Data rollover'],
    speedLabel: '50GB',
    eligibleProductIds: [],
    popular: true,
    serviceType: 'sim',
    publicPricePrefix: '',
    publicSetupText: '',
    publicTagline: 'For the social media enthusiasts',
    publicFeatures: ['50GB 5G data', 'Unlimited UK calls', 'Unlimited texts', '30GB EU roaming', 'No contracts - cancel anytime', 'Data rollover'],
    publicDisclaimer: '',
  },
  {
    id: 'sim-unlimited',
    publicTitle: 'Unlimited',
    category: 'SIM',
    tagline: 'Never worry about data again',
    description: 'Never worry about data again',
    features: ['Unlimited 5G data', 'Unlimited UK calls', 'Unlimited texts', '50GB EU roaming', 'No contracts - cancel anytime', 'Free intl calls (50 countries)'],
    speedLabel: '∞',
    eligibleProductIds: [],
    popular: false,
    serviceType: 'sim',
    publicPricePrefix: '',
    publicSetupText: '',
    publicTagline: 'Never worry about data again',
    publicFeatures: ['Unlimited 5G data', 'Unlimited UK calls', 'Unlimited texts', '50GB EU roaming', 'No contracts - cancel anytime', 'Free intl calls (50 countries)'],
    publicDisclaimer: '',
  },
];
