import type { RetailCardDef } from './types';

// ── Public Retail Card Definitions ──
// Maps to catalogue products by eligibleProductIds.
// The UI renders these cards — never raw catalogue data.

export const broadbandRetailCards: RetailCardDef[] = [
  {
    id: 'essential',
    publicTitle: 'ESSENTIAL',
    category: 'Essentials',
    tagline: 'Perfect for browsing, emails, and light streaming',
    description: 'Perfect for browsing, emails, and light streaming',
    features: [
      'Up to 80Mbps download',
      'Unlimited usage',
      'Free router included',
      'No contracts - cancel anytime',
      '24/7 UK-based support',
      'Free installation',
    ],
    speedLabel: 'Up to 80Mbps',
    eligibleProductIds: ['sogea-40-10-1m', 'sogea-80-20-1m', 'fttp-80-20-tt'],
    popular: false,
    serviceType: 'broadband',
    publicPricePrefix: 'From',
    publicSetupText: 'Setup may apply depending on line status',
    publicTagline: 'Perfect for browsing, emails, and light streaming',
    publicFeatures: [
      'Up to 80Mbps download',
      'Unlimited usage',
      'Free router included',
      'No contracts - cancel anytime',
      '24/7 UK-based support',
      'Free installation',
    ],
    publicDisclaimer: '',
  },
  {
    id: 'superfast',
    publicTitle: 'SUPERFAST',
    category: 'Everyday Fibre',
    tagline: 'Ideal for families, Netflix, and everyday use',
    description: 'Ideal for families, Netflix, and everyday use',
    features: [
      'Up to 330Mbps download',
      'Unlimited usage',
      'Premium router included',
      'No contracts - cancel anytime',
      'Priority 24/7 support',
      'Free installation',
    ],
    speedLabel: 'Up to 330Mbps',
    eligibleProductIds: ['fttp-160-tt', 'fttp-220-tt', 'fttp-330-tt'],
    popular: true,
    serviceType: 'broadband',
    publicPricePrefix: 'From',
    publicSetupText: '',
    publicTagline: 'Ideal for families, Netflix, and everyday use',
    publicFeatures: [
      'Up to 330Mbps download',
      'Unlimited usage',
      'Premium router included',
      'No contracts - cancel anytime',
      'Priority 24/7 support',
      'Free installation',
    ],
    publicDisclaimer: '',
  },
  {
    id: 'ultrafast',
    publicTitle: 'ULTRAFAST',
    category: 'Ultra Fibre',
    tagline: 'Great for gamers, work-from-home, and heavy usage',
    description: 'Great for gamers, work-from-home, and heavy usage',
    features: [
      'Up to 550Mbps download',
      'Unlimited usage',
      'WiFi 6 router included',
      'No contracts - cancel anytime',
      'Priority 24/7 support',
      'Free static IP included',
    ],
    speedLabel: 'Up to 550Mbps',
    eligibleProductIds: ['fttp-500-tt', 'fttp-550-cf'],
    popular: false,
    serviceType: 'broadband',
    publicPricePrefix: 'From',
    publicSetupText: '',
    publicTagline: 'For gamers, streamers, and people who work from home',
    publicFeatures: [
      'Up to 550Mbps download',
      'Unlimited usage',
      'WiFi 6 router included',
      'No contracts - cancel anytime',
      'Priority 24/7 support',
      'Free static IP included',
    ],
    publicDisclaimer: '',
  },
  {
    id: 'gigabit',
    publicTitle: 'GIGABIT',
    category: 'Gigafast',
    tagline: 'The fastest internet money can buy. Period.',
    description: 'The fastest internet money can buy. Period.',
    features: [
      'Up to 1Gbps download',
      'Unlimited usage',
      'WiFi 6E mesh system',
      'No contracts - cancel anytime',
      'Dedicated support line',
      'Free static IP included',
    ],
    speedLabel: 'Up to 1Gbps',
    eligibleProductIds: ['fttp-1000-tt', 'fttp-1000-cf'],
    popular: false,
    serviceType: 'broadband',
    publicPricePrefix: 'From',
    publicSetupText: '',
    publicTagline: 'The fastest internet money can buy. Period.',
    publicFeatures: [
      'Up to 1Gbps download',
      'Unlimited usage',
      'WiFi 6E mesh system',
      'No contracts - cancel anytime',
      'Dedicated support line',
      'Free static IP included',
    ],
    publicDisclaimer: '',
  },
];

export const landlineRetailCard: RetailCardDef = {
  id: 'digital-voice',
  publicTitle: 'Digital Voice Line',
  category: 'Digital Home Phone',
  tagline: 'Digital home phone that works through your broadband',
  description: 'Digital home phone that works through your broadband',
  features: [
    'Digital voice line included',
    'Crystal clear HD calls',
    'Caller display',
    'Free voicemail',
    'No contracts - cancel anytime',
    'Works with standard home phones',
  ],
  speedLabel: '',
  eligibleProductIds: ['home-phone-payg'],
  popular: true,
  serviceType: 'landline',
  publicPricePrefix: 'From',
  publicSetupText: '',
  publicTagline: 'Digital home phone that works through your broadband',
  publicFeatures: [
    'Digital voice line included',
    'Crystal clear HD calls',
    'Caller display',
    'Free voicemail',
    'No contracts - cancel anytime',
    'Works with standard home phones',
  ],
  publicDisclaimer: '',
};

// SIM retail cards — no ICUK data uploaded, keep current prices exactly
export const simRetailCards: RetailCardDef[] = [
  {
    id: 'sim-starter',
    publicTitle: 'Starter',
    category: 'SIM',
    tagline: 'For light users and second phones',
    description: 'For light users and second phones',
    features: ['5GB 5G data', 'Unlimited UK calls', 'Unlimited texts', 'EU roaming included', 'No contracts - cancel anytime', 'Free SIM delivery'],
    speedLabel: '5GB',
    eligibleProductIds: [],
    popular: false,
    serviceType: 'sim',
    publicPricePrefix: '',
    publicSetupText: '',
    publicTagline: 'For light users and second phones',
    publicFeatures: ['5GB 5G data', 'Unlimited UK calls', 'Unlimited texts', 'EU roaming included', 'No contracts - cancel anytime', 'Free SIM delivery'],
    publicDisclaimer: '',
  },
  {
    id: 'sim-essential',
    publicTitle: 'Essential',
    category: 'SIM',
    tagline: 'Perfect for everyday use',
    description: 'Perfect for everyday use',
    features: ['15GB 5G data', 'Unlimited UK calls', 'Unlimited texts', 'EU roaming included', 'No contracts - cancel anytime', 'Data rollover'],
    speedLabel: '15GB',
    eligibleProductIds: [],
    popular: false,
    serviceType: 'sim',
    publicPricePrefix: '',
    publicSetupText: '',
    publicTagline: 'Perfect for everyday use',
    publicFeatures: ['15GB 5G data', 'Unlimited UK calls', 'Unlimited texts', 'EU roaming included', 'No contracts - cancel anytime', 'Data rollover'],
    publicDisclaimer: '',
  },
  {
    id: 'sim-plus',
    publicTitle: 'Plus',
    category: 'SIM',
    tagline: 'For the social media enthusiasts',
    description: 'For the social media enthusiasts',
    features: ['50GB 5G data', 'Unlimited UK calls', 'Unlimited texts', '30GB EU roaming', 'No contracts - cancel anytime', 'Data rollover'],
    speedLabel: '50GB',
    eligibleProductIds: [],
    popular: true,
    serviceType: 'sim',
    publicPricePrefix: '',
    publicSetupText: '',
    publicTagline: 'For the social media enthusiasts',
    publicFeatures: ['50GB 5G data', 'Unlimited UK calls', 'Unlimited texts', '30GB EU roaming', 'No contracts - cancel anytime', 'Data rollover'],
    publicDisclaimer: '',
  },
  {
    id: 'sim-unlimited',
    publicTitle: 'Unlimited',
    category: 'SIM',
    tagline: 'Never worry about data again',
    description: 'Never worry about data again',
    features: ['Unlimited 5G data', 'Unlimited UK calls', 'Unlimited texts', '50GB EU roaming', 'No contracts - cancel anytime', 'Free intl calls (50 countries)'],
    speedLabel: '∞',
    eligibleProductIds: [],
    popular: false,
    serviceType: 'sim',
    publicPricePrefix: '',
    publicSetupText: '',
    publicTagline: 'Never worry about data again',
    publicFeatures: ['Unlimited 5G data', 'Unlimited UK calls', 'Unlimited texts', '50GB EU roaming', 'No contracts - cancel anytime', 'Free intl calls (50 countries)'],
    publicDisclaimer: '',
  },
];
